### ISSUE TITLE
tests/CI fail for double mut borrow

### ISSUE THREAD

**Issue by PThorpe92** [tursodatabase/limbo#484]
While working on #476: after submitting the PR and then later force pushing some small changes, I noticed one of the build tests failed for a `BorrowMutError`. However upon my next push it re-ran and passed fine. Since my changes didn't affect anything that would be running in the tests, I figured it was unlikely to be the cause.

Now I see CI failed on [latest push](https://github.com/tursodatabase/limbo/actions/runs/12338996546/job/34434652905) for the same issue.

Can't reproduce it locally, as I ran the relevant test for 10 mins in a loop locally and not 1 failure. Both times it was the Ubuntu runner.

**Comment by pereman2** [comment]
This should be fixed here https://github.com/tursodatabase/limbo/pull/468
