### ISSUE TITLE
UUID support?

### ISSUE THREAD

**Issue by StayBlue** [tursodatabase/limbo#509]
One of the nice things about libSQL is that it supports UUIDs through an (experimental) extension. Are there any plans to have this feature in Limbo?

**Comment by pereman2** [comment]
If it is in libsql, it most likely means we will get to it in the future. At the end of the day, we want the same things.

**Comment by StayBlue** [comment]
With #518 being merged, should this be closed?

**Comment by pereman2** [comment]
I think so @PThorpe92, is something missing?

**Comment by PThorpe92** [comment]
Everything from the `sqlean` ext is all there, so should be all set to close :+1:
