### ISSUE TITLE
Run `clippy` in `ci`

### ISSUE THREAD

**Issue by cospectrum** [tursodatabase/limbo#542]
The contribution guide suggests running `clippy`. There are several pull requests that use the `cargo clippy fix`. But at the same time, I did not find a `ci` job that would check `clippy`, which looks strange.

**Comment by travenin** [comment]
Running clippy in CI for every PR would be very good idea to keep codebase in better shape. However, there are quite a lot of issues in the main branch currently. Majority of them should be fixed first.

However, I am interested in working on this issue.

**Comment by pereman2** [comment]
I've been avoiding this as much as possible  because I hate some things from clippy, but overall it is a good direction. I would suggest using this command as the entrypoint `cargo clippy -- -A clippy::all -W clippy::correctness -W clippy::perf -W clippy::suspicious --deny=warnings`

**Comment by travenin** [comment]
Good point. It's not necessary to keep clippy perfectly happy. Your suggested command looks good place to start. :+1:

**Comment by penberg** [comment]
We run Clippy now as part of the CI as of f6cd7075449c0142bb11b43c09ba176b8a2f740e.
